---
## Default Elasticsearch configuration from elasticsearch-docker.
## from https://github.com/elastic/dockerfiles/blob/7.8/elasticsearch/config/elasticsearch.yml
#
cluster.name: "docker-cluster"
network.host: 0.0.0.0

## Use single node discovery in order to disable production mode and avoid bootstrap checks
## see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
#
discovery.type: single-node
