---
## Default Kibana configuration from kibana-docker.
## from https://github.com/elastic/dockerfiles/blob/7.8/kibana/config/kibana.yml
#
server.name: kibana
server.host: "0"
elasticsearch.hosts: [ "http://elasticsearch:9200" ]
monitoring.ui.container.elasticsearch.enabled: true
